export const LEVELS: {
  name: string;
  terminals: number;
  dataIndex: number | null;
}[] = [
  { name: "Arrival", terminals: 4, dataIndex: 0 },
  { name: "Bigger Guns Nearby", terminals: 3, dataIndex: 1 },
  { name: "Never Burn Money", terminals: 5, dataIndex: 2 },
  { name: "Defend THIS!", terminals: 5, dataIndex: 3 },
  { name: "Couch Fishing", terminals: 3, dataIndex: 4 },
  { name: "The Rose", terminals: 4, dataIndex: 5 },
  {
    name: "Smells Like Napalm, Tastes Like Chicken!",
    terminals: 4,
    dataIndex: 6,
  },
  { name: "Cool Fusion", terminals: 2, dataIndex: 7 },
  { name: "G4 Sunbathing", terminals: 2, dataIndex: 8 },
  { name: "Blaspheme Quarantine", terminals: 4, dataIndex: 9 },
  { name: "Bob-B-Q", terminals: 1, dataIndex: 10 },
  { name: "Shake Before Using…", terminals: 3, dataIndex: 11 },
  { name: "Fire! Fire! Fire! Fire! Fire!", terminals: 2, dataIndex: 12 },
  { name: "Colony Ship For Sale, Cheap", terminals: 3, dataIndex: 13 },
  { name: "Habe Quiddam", terminals: 2, dataIndex: 14 },
  { name: "Neither High nor Low", terminals: 2, dataIndex: 15 },
  { name: "Pfhor Your Eyes Only…", terminals: 0, dataIndex: null },
  { name: "No Artificial Colors", terminals: 1, dataIndex: 16 },
  { name: "Unpfhorgiven", terminals: 0, dataIndex: null },
  { name: "Two Times Two Equals…", terminals: 0, dataIndex: null },
  {
    name: "Beware of Low-Flying Defense Drones…",
    terminals: 3,
    dataIndex: 17,
  },
  { name: "Eupfhoria", terminals: 0, dataIndex: null },
  { name: "Pfhoraphobia", terminals: 0, dataIndex: null },
  { name: "Ain't Got Time Pfhor This…", terminals: 0, dataIndex: null },
  { name: "Welcome to the Revolution…", terminals: 3, dataIndex: 18 },
  { name: "Try again", terminals: 3, dataIndex: 19 },
  { name: "Ingue Ferroque", terminals: 3, dataIndex: 20 },
  { name: "Mars Needs Women", terminals: 0, dataIndex: null },
  { name: "Carnage Palace Deeee-Luxe", terminals: 0, dataIndex: null },
  { name: "5-D space", terminals: 0, dataIndex: null },
  { name: "Arena", terminals: 0, dataIndex: null },
  { name: "E equals MC WHAT!!", terminals: 0, dataIndex: null },
  { name: "Showered With Grenades", terminals: 0, dataIndex: null },
  { name: "Spiral Insanity", terminals: 0, dataIndex: null },
  { name: "Waldo World Arena", terminals: 0, dataIndex: null },
  { name: "What Goes Up, Must Come Down", terminals: 0, dataIndex: null },
  { name: "You don't need to see my I.D.", terminals: 0, dataIndex: null },
];
