export const LEVELS = [
  { name: "Arrival", terminals: 4 },
  { name: "Bigger Guns Nearby", terminals: 3 },
  { name: "Never Burn Money", terminals: 5 },
  { name: "Defend THIS!", terminals: 5 },
  { name: "Couch Fishing", terminals: 3 },
  { name: "The Rose", terminals: 4 },
  { name: "Smells Like Napalm, Tastes Like Chicken!", terminals: 4 },
  { name: "Cool Fusion", terminals: 2 },
  { name: "G4 Sunbathing", terminals: 2 },
  { name: "Blaspheme Quarantine", terminals: 4 },
  { name: "Bob-B-Q", terminals: 1 },
  { name: "Shake Before Using…", terminals: 3 },
  { name: "Fire! Fire! Fire! Fire! Fire!", terminals: 2 },
  { name: "Colony Ship For Sale, Cheap", terminals: 3 },
  { name: "Habe Quiddam", terminals: 2 },
  { name: "Neither High nor Low", terminals: 2 },
  { name: "Pfhor Your Eyes Only…", terminals: 0 },
  { name: "No Artificial Colors", terminals: 1 },
  { name: "Unpfhorgiven", terminals: 0 },
  { name: "Two Times Two Equals…", terminals: 0 },
  { name: "Beware of Low-Flying Defense Drones…", terminals: 3 },
  { name: "Eupfhoria", terminals: 0 },
  { name: "Pfhoraphobia", terminals: 0 },
  { name: "Ain't Got Time Pfhor This…", terminals: 0 },
  { name: "Welcome to the Revolution…", terminals: 3 },
  { name: "Try again", terminals: 3 },
  { name: "Ingue Ferroque", terminals: 3 },
  { name: "Mars Needs Women", terminals: 0 },
  { name: "Carnage Palace Deeee-Luxe", terminals: 0 },
  { name: "5-D space", terminals: 0 },
  { name: "Arena", terminals: 0 },
  { name: "E equals MC WHAT!!", terminals: 0 },
  { name: "Showered With Grenades", terminals: 0 },
  { name: "Spiral Insanity", terminals: 0 },
  { name: "Waldo World Arena", terminals: 0 },
  { name: "What Goes Up, Must Come Down", terminals: 0 },
  { name: "You don't need to see my I.D.", terminals: 0 },
];
